name: Java CI with Maven + Deploy to Scaleway

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: surf_spots_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        env:
          DB_USERNAME: postgres
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/surf_spots_db
        run: mvn clean package -DskipTests --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Scaleway Container Registry
        run: echo "${{ secrets.SCW_SECRET_KEY }}" | docker login rg.fr-par.scw.cloud/surfspots -u nologin --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t surf-spots-api .
          docker tag surf-spots-api:latest rg.fr-par.scw.cloud/surfspots/surf-spots-api:latest
          docker push rg.fr-par.scw.cloud/surfspots/surf-spots-api:latest
